# Staging configuration for the original development Shopify app

client_id = "530ea6396a8bbc045959441138ad344a"
name = "OMS Hook Connector"
application_url = "https://oms-hook-connector-staging.up.railway.app"
embedded = true

[access_scopes]
scopes = "read_orders"
optional_scopes = []
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://oms-hook-connector-staging.up.railway.app/auth/callback"
]

[webhooks]
api_version = "2026-07"

[[webhooks.subscriptions]]
topics = ["orders/create"]
uri = "/webhooks/orders/create"

[[webhooks.subscriptions]]
topics = ["app/uninstalled"]
uri = "/webhooks/app/uninstalled"

[[webhooks.subscriptions]]
topics = ["app/scopes_update"]
uri = "/webhooks/app/scopes_update"

[[webhooks.subscriptions]]
compliance_topics = [
  "customers/data_request",
  "customers/redact",
  "shop/redact"
]
uri = "/webhooks/compliance"

[build]
automatically_update_urls_on_dev = false